package capadelcliente;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import extras.ClaseValidacion;
import capadenegocio.Estudiante;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author tania
 */
public class IngresarPartido extends javax.swing.JFrame {

    int xMouse, yMouse;

    public IngresarPartido() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nlista = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        idPresidente = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        slogan = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        registrarb = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        ebt = new javax.swing.JPanel();
        ext = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(230, 120));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(150, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 70));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/imagen/udla_logo_blanco (1).png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(706, 6, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto Medium", 0, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Comité");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 0, 180, 30));

        jLabel8.setFont(new java.awt.Font("Roboto Medium", 0, 32)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ingresar Partido");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 284, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 800, 70));

        jLabel2.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel2.setText("Eslogan:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel4.setText("Nombre de la lista:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel5.setText("Presidente del partido (id Banner):");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        nlista.setForeground(new java.awt.Color(204, 204, 204));
        nlista.setText("Ingrese el nombre de la lista");
        nlista.setBorder(null);
        nlista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nlistaMousePressed(evt);
            }
        });
        nlista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nlistaActionPerformed(evt);
            }
        });
        jPanel1.add(nlista, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 230, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 280, 10));

        idPresidente.setForeground(new java.awt.Color(204, 204, 204));
        idPresidente.setText("Ingrese el presidente del partido");
        idPresidente.setBorder(null);
        idPresidente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                idPresidenteMousePressed(evt);
            }
        });
        jPanel1.add(idPresidente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 230, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 280, 10));

        slogan.setForeground(new java.awt.Color(204, 204, 204));
        slogan.setText("Eslogan");
        slogan.setBorder(null);
        slogan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sloganMousePressed(evt);
            }
        });
        jPanel1.add(slogan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 230, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 280, 10));

        registrarb.setBackground(new java.awt.Color(150, 0, 0));
        registrarb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrarCandidato(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registrarbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registrarbMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("REGISTRAR");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrarCandidato(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });

        javax.swing.GroupLayout registrarbLayout = new javax.swing.GroupLayout(registrarb);
        registrarb.setLayout(registrarbLayout);
        registrarbLayout.setHorizontalGroup(
            registrarbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        registrarbLayout.setVerticalGroup(
            registrarbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrarbLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(registrarb, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 150, 30));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel4MouseDragged(evt);
            }
        });
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel4MousePressed(evt);
            }
        });

        ebt.setBackground(new java.awt.Color(255, 255, 255));
        ebt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ebt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ebtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ebtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ebtMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ebtMousePressed(evt);
            }
        });

        ext.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        ext.setText("X");
        ext.setPreferredSize(new java.awt.Dimension(40, 10));
        ext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                extMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                extMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                extMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ebtLayout = new javax.swing.GroupLayout(ebt);
        ebt.setLayout(ebtLayout);
        ebtLayout.setHorizontalGroup(
            ebtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ebtLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ext, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ebtLayout.setVerticalGroup(
            ebtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ext, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(ebt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 765, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ebt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 30));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel5MouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel11.setText("<");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(14, 14, 14))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 40, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MousePressed

    private void jPanel4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MouseDragged

    private void ebtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ebtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ebtMousePressed

    private void ebtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ebtMouseClicked
        System.exit(0); // TODO add your handling code here:
    }//GEN-LAST:event_ebtMouseClicked

    private void ebtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ebtMouseEntered
        ebt.setBackground(new Color(150, 0, 0));
        ext.setForeground(Color.white);        // TODO add your handling code here:
    }//GEN-LAST:event_ebtMouseEntered

    private void ebtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ebtMouseExited
        ebt.setBackground(Color.white);
        ext.setForeground(Color.black);  // TODO add your handling code here:
    }//GEN-LAST:event_ebtMouseExited

    private void nlistaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nlistaMousePressed
        if (nlista.getText().equals("Ingrese el nombre de la lista")) {
            nlista.setText("");//Ingrese el nombre de la lista
        }
        nlista.setForeground(Color.black);
        if (idPresidente.getText().isEmpty()) {
            idPresidente.setText("Ingrese el presidente del partido");
        }
        idPresidente.setForeground(Color.gray);
        if (slogan.getText().isEmpty()) {
            slogan.setText("Eslogan");// TODO add your handling code here:
        }
        slogan.setForeground(Color.gray);
    }//GEN-LAST:event_nlistaMousePressed

    private void nlistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nlistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nlistaActionPerformed

    private void idPresidenteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idPresidenteMousePressed
        if (nlista.getText().isEmpty()) {
            nlista.setText("Ingrese el nombre de la lista");
        }
        nlista.setForeground(Color.gray);//Ingrese el nombre de la lista
        if (idPresidente.getText().equals("Ingrese el presidente del partido")) {
            idPresidente.setText("");
        }
        idPresidente.setForeground(Color.black);
        if (slogan.getText().isEmpty()) {
            slogan.setText("Eslogan");
        }
        slogan.setForeground(Color.gray);// TODO add your handling code here:
    }//GEN-LAST:event_idPresidenteMousePressed

    private void sloganMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sloganMousePressed
        if (nlista.getText().isEmpty()) {
            nlista.setText("Ingrese el nombre de la lista");
        }
        nlista.setForeground(Color.gray);//Ingrese el nombre de la lista
        if (idPresidente.getText().isEmpty()) {
            idPresidente.setText("Ingrese el presidente del partido");
        }
        idPresidente.setForeground(Color.gray);
        if (slogan.getText().equals("Eslogan")) {
            slogan.setText("");
        }
        slogan.setForeground(Color.black);// TODO add your handling code here:
    }//GEN-LAST:event_sloganMousePressed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        Manejoasociacionesycandidatos j = new Manejoasociacionesycandidatos();
        j.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
        jPanel5.setBackground(new Color(150, 0, 0));
        jLabel11.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
        jPanel5.setBackground(Color.WHITE);
        jLabel11.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel11MouseExited

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        Manejoasociacionesycandidatos j = new Manejoasociacionesycandidatos();
        j.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jPanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseEntered
        jPanel5.setBackground(new Color(150, 0, 0));
        jLabel11.setForeground(Color.WHITE);
    }//GEN-LAST:event_jPanel5MouseEntered

    private void jPanel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseExited
        jPanel5.setBackground(Color.WHITE);
        jLabel11.setForeground(Color.BLACK);
    }//GEN-LAST:event_jPanel5MouseExited

    private void extMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extMouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_extMouseClicked

    private void extMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extMouseExited
        ebt.setBackground(Color.white);
        ext.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_extMouseExited

    private void extMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extMouseEntered
        ebt.setBackground(new Color(150, 0, 0));
        ext.setForeground(Color.white);         // TODO add your handling code here:
    }//GEN-LAST:event_extMouseEntered

    private void registrarbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarbMouseExited
        registrarb.setBackground(new Color(150, 0, 0)); // TODO add your handling code here:
    }//GEN-LAST:event_registrarbMouseExited

    private void registrarbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarbMouseEntered
        registrarb.setBackground(new Color(200, 0, 0)); // TODO add your handling code here:
    }//GEN-LAST:event_registrarbMouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        registrarb.setBackground(new Color(150, 0, 0)); // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered

        registrarb.setBackground(new Color(200, 0, 0)); // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseEntered

    private void registrarCandidato(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarCandidato
        /**
         * Validación de los parámtros ingresados por el usuario
         */
        Estudiante e = Logueo.padron.buscarEstudiante(idPresidente.getText());
        boolean nombreCorrecto = ClaseValidacion.validarLongitusString(nlista.getText(), 50);
        boolean idCorrecto = ClaseValidacion.validarUsuario(idPresidente.getText());
        boolean sloganCorrecto = ClaseValidacion.validarLongitusString(slogan.getText(), 150);
        boolean idExiste = e != null;

        /**
         * Acciones tomadas según las validaciones
         */
        if (nombreCorrecto && idCorrecto && sloganCorrecto && idExiste) {
            /**
             * Verifica que no existan ya la Asociación o el presidente esté con
             * otra asociación
             */
            boolean existe = null != Logueo.padron.buscarAsociacion(nlista.getText());
            boolean presidenteRegistrado = false;
            for (capadenegocio.Asociacion a : Logueo.padron.getAsociaciones()) {
                if (a.getPresidenteAsociacion().equals(idPresidente.getText())) {
                    presidenteRegistrado = true;
                    break;
                }
            }

            /**
             * Toma acciones según lo anterior
             */
            if (!existe && !presidenteRegistrado) {

                int result = JOptionPane.showConfirmDialog(null,
                        "Información del Estudiante\n\n"
                        + "Nombres: " + e.getNombre() + " " + e.getApellido()
                        + "\nFacultad: " + e.getFacultad().toString()
                        + "\nPromedio General: " + e.getPromedioGeneral()
                        + "\nEstado Diciplinario: " + ((e.isEstadoDiciplinario()) ? "en orden" : "falta(s) registrada(s)"), "Confirmación", JOptionPane.YES_NO_OPTION);

                if (result == JOptionPane.YES_OPTION) {
                    if (Logueo.con.agregarPartido(nlista.getText(), idPresidente.getText(), slogan.getText())) {
                        Logueo.padron.agregarAsociacion(nlista.getText(), idPresidente.getText(), slogan.getText());
                        JOptionPane.showMessageDialog(null, "Se agregó correctamente la asociación " + nlista.getText());
                        slogan.setText("");
                        idPresidente.setText("");
                        nlista.setText("");
                    } else {
                        JOptionPane.showMessageDialog(null, "Hubo un problema registrando la asociación, \ninténtelo de nuevo más tarde");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "No se agregó la asociación.");
                }
            } else {
                JOptionPane.showMessageDialog(null, "El nombre o el presidente ya se encuentran registrados");
            }
        } else if (!idExiste) {
            JOptionPane.showMessageDialog(null, "El id ingresado no corresponde a ningún estudiante");
        } else {
            JOptionPane.showMessageDialog(null, "Alguno de los campos se llenó de forma incorrecta. \nRecuerda que el nombre debe tener máximo 50 caracteres y el eslogan 150");
        }
    }//GEN-LAST:event_registrarCandidato

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarPartido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarPartido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarPartido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarPartido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresarPartido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ebt;
    private javax.swing.JLabel ext;
    private javax.swing.JTextField idPresidente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField nlista;
    private javax.swing.JPanel registrarb;
    private javax.swing.JTextField slogan;
    // End of variables declaration//GEN-END:variables
}
