package capadelcliente;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import extras.ClaseValidacion;
import capadenegocio.Dignidades;
import capadenegocio.Estudiante;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author tania
 */
public class PostularCandidato extends javax.swing.JFrame {

    /**
     * Creates new form PostularCandidato
     */
    int xMouse, yMouse;

    public PostularCandidato() {
        initComponents();
        this.setLocationRelativeTo(null);
        for (capadenegocio.Asociacion a : Logueo.padron.getAsociaciones()) {
            if(!a.getNombre().equals("blanco")){
                asociacionesRegistradas.addItem(a.getNombre());
            }
        }
        asociacionesRegistradas.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        ext = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        idbanner = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        Ingresarb = new javax.swing.JPanel();
        ingresart = new javax.swing.JLabel();
        asociacionesRegistradas = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        dignidades = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(230, 120));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 30));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.setPreferredSize(new java.awt.Dimension(35, 30));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel4MouseExited(evt);
            }
        });

        ext.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        ext.setText("X");
        ext.setPreferredSize(new java.awt.Dimension(40, 10));
        ext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                extMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                extMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                extMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ext, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ext, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 30));

        jPanel3.setBackground(new java.awt.Color(150, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/imagen/udla_logo_blanco (1).png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 6, 90, 40));

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Comité");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 0, 180, 30));

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingresar candidatos");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 536, 72));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 800, 70));

        jLabel7.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel7.setText("Asociación:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 80, -1));

        jLabel8.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel8.setText("ID Banner:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 80, -1));

        idbanner.setForeground(new java.awt.Color(204, 204, 204));
        idbanner.setText("Ingrese el ID banner");
        idbanner.setBorder(null);
        idbanner.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        idbanner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                idbannerMousePressed(evt);
            }
        });
        idbanner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idbannerActionPerformed(evt);
            }
        });
        jPanel1.add(idbanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 230, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 280, 20));

        Ingresarb.setBackground(new java.awt.Color(150, 0, 0));
        Ingresarb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresarCandidato(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IngresarbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IngresarbMouseExited(evt);
            }
        });

        ingresart.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        ingresart.setForeground(new java.awt.Color(255, 255, 255));
        ingresart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ingresart.setText("Ingresar");
        ingresart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingresart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresarCandidato(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ingresartMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ingresartMouseExited(evt);
            }
        });

        javax.swing.GroupLayout IngresarbLayout = new javax.swing.GroupLayout(Ingresarb);
        Ingresarb.setLayout(IngresarbLayout);
        IngresarbLayout.setHorizontalGroup(
            IngresarbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IngresarbLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ingresart, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        IngresarbLayout.setVerticalGroup(
            IngresarbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IngresarbLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ingresart, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(Ingresarb, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        asociacionesRegistradas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(asociacionesRegistradas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 290, 20));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel5MouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel11.setText("<");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(14, 14, 14))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 40, 30));

        jLabel9.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel9.setText("Dignidad:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 80, -1));

        dignidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Presidente de ASEUDLA general", "Vicepresidente de ASEUDLA general", "Presidente de ASEUDLA facultad", "Vicepresidente de ASEUDLA facultad" }));
        dignidades.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(dignidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 290, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idbannerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idbannerMousePressed

        if (idbanner.getText().equals("Ingrese el ID banner")) {
            idbanner.setText("");
        }
        idbanner.setForeground(Color.black); // TODO add your handling code here:
    }//GEN-LAST:event_idbannerMousePressed

    private void idbannerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idbannerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idbannerActionPerformed

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MouseClicked

    private void extMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extMouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_extMouseClicked

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered
        jPanel4.setBackground(new Color(150, 0, 0));
        ext.setForeground(Color.white);     // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MouseEntered

    private void jPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseExited
        jPanel4.setBackground(Color.white);
        ext.setForeground(Color.black);    // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MouseExited

    private void ingresartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresartMouseEntered
        Ingresarb.setBackground(new Color(200, 0, 0));        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresartMouseEntered

    private void IngresarbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresarbMouseEntered
        Ingresarb.setBackground(new Color(200, 0, 0)); // TODO add your handling code here:
    }//GEN-LAST:event_IngresarbMouseEntered

    private void IngresarbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresarbMouseExited
        Ingresarb.setBackground(new Color(150, 0, 0));        // TODO add your handling code here:
    }//GEN-LAST:event_IngresarbMouseExited

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();         // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseDragged

    private void extMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extMouseEntered
        jPanel4.setBackground(new Color(150, 0, 0));
        ext.setForeground(Color.white);


    }//GEN-LAST:event_extMouseEntered

    private void extMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extMouseExited
        jPanel4.setBackground(Color.white);
        ext.setForeground(Color.black);     // TODO add your handling code here:
    }//GEN-LAST:event_extMouseExited

    private void ingresartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresartMouseExited
        Ingresarb.setBackground(new Color(150, 0, 0));        // TODO add your handling code here:
    }//GEN-LAST:event_ingresartMouseExited

    private void jPanel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseExited
        jPanel5.setBackground(Color.WHITE);
        jLabel11.setForeground(Color.BLACK);
    }//GEN-LAST:event_jPanel5MouseExited

    private void jPanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseEntered
        jPanel5.setBackground(new Color(150, 0, 0));
        jLabel11.setForeground(Color.WHITE);
    }//GEN-LAST:event_jPanel5MouseEntered

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        Manejoasociacionesycandidatos j = new Manejoasociacionesycandidatos();
        j.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
        jPanel5.setBackground(Color.WHITE);
        jLabel11.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel11MouseExited

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
        jPanel5.setBackground(new Color(150, 0, 0));
        jLabel11.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        Manejoasociacionesycandidatos j = new Manejoasociacionesycandidatos();
        j.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void ingresarCandidato(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarCandidato
        int dignidad = dignidades.getSelectedIndex();
        String asociacion = asociacionesRegistradas.getSelectedItem().toString();
        String id = idbanner.getText();

        boolean idCorrecto = ClaseValidacion.validarUsuario(id);
        if (idCorrecto) {
            Estudiante e = Logueo.padron.buscarEstudiante(id);
            boolean idExiste = e != null;
            if (idExiste) {
                if (!Logueo.padron.existeCandidatoId(id)) {
                    Dignidades.Dignidad d;
                    d = (dignidad == 0 || dignidad == 2) ? Dignidades.Dignidad.PRESIDENTE : Dignidades.Dignidad.VICEPRESIDENTE;
                    if (dignidad == 0) {
                        boolean dignidadRegistrada;
                        dignidadRegistrada = Logueo.padron.buscarAsociacion(asociacion).getPresidenteGeneral() != null;

                        if (!dignidadRegistrada) {
                            int result = JOptionPane.showConfirmDialog(null,
                                    "Información del Estudiante\n\n"
                                    + "Nombres: " + e.getNombre() + " " + e.getApellido()
                                    + "\nFacultad: " + e.getFacultad().toString()
                                    + "\nPromedio General: " + e.getPromedioGeneral()
                                    + "\nEstado Diciplinario: " + ((e.isEstadoDiciplinario()) ? "en orden" : "falta(s) registrada(s)"), "Confirmación", JOptionPane.YES_NO_OPTION);

                            if (result == JOptionPane.YES_OPTION) {
                                if (Logueo.con.agregarCandidatoGeneral(id, asociacion, true)) {
                                    Logueo.padron.buscarAsociacion(asociacion).agregarCandidatoGeneral(id, true);
                                    JOptionPane.showMessageDialog(null, "Candidato agregado con éxito en"
                                            + "la asociación " + asociacion + " para la dignidad " + dignidades.getSelectedItem().toString());
                                } else {
                                    JOptionPane.showMessageDialog(null, "No se agregó el candidato, inténtelo de nuevo más tarde");
                                }
                            } else {
                                JOptionPane.showMessageDialog(null, "No se agregó el candidato");
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Un candidato para esta digniddad ya\n"
                                    + "se encuentra registrado en este partido");
                        }
                    } else if (dignidad == 1) {
                        boolean dignidadRegistrada;
                        dignidadRegistrada = Logueo.padron.buscarAsociacion(asociacion).getVicepresidenteGeneral() != null;
                        if (!dignidadRegistrada) {
                            int result = JOptionPane.showConfirmDialog(null,
                                    "Información del Estudiante\n\n"
                                    + "Nombres: " + e.getNombre() + " " + e.getApellido()
                                    + "\nFacultad: " + e.getFacultad().toString()
                                    + "\nPromedio General: " + e.getPromedioGeneral()
                                    + "\nEstado Diciplinario: " + ((e.isEstadoDiciplinario()) ? "en orden" : "falta(s) registrada(s)"), "Confirmación", JOptionPane.YES_NO_OPTION);

                            if (result == JOptionPane.YES_OPTION) {
                                if (Logueo.con.agregarCandidatoGeneral(id, asociacion, false)) {
                                    Logueo.padron.buscarAsociacion(asociacion).agregarCandidatoGeneral(id, false);
                                    JOptionPane.showMessageDialog(null, "Candidato agregado con éxito en"
                                            + "la asociación " + asociacion + " para la dignidad " + dignidades.getSelectedItem().toString());
                                } else {
                                    JOptionPane.showMessageDialog(null, "No se agregó el candidato, inténtelo de nuevo más tarde");
                                }

                            } else {
                                JOptionPane.showMessageDialog(null, "No se agregó el candidato");
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Un candidato para esta digniddad ya\n"
                                    + "se encuentra registrado en este partido");
                        }
                    } else if (dignidad == 2) {
                        boolean dignidadRegistrada;
                        dignidadRegistrada = Logueo.padron.buscarAsociacion(asociacion).
                                getPresidentesFacultad().get(e.getFacultad()) != null;
                        if (!dignidadRegistrada) {
                            int result = JOptionPane.showConfirmDialog(null,
                                    "Información del Estudiante\n\n"
                                    + "Nombres: " + e.getNombre() + " " + e.getApellido()
                                    + "\nFacultad: " + e.getFacultad().toString()
                                    + "\nPromedio General: " + e.getPromedioGeneral()
                                    + "\nEstado Diciplinario: " + ((e.isEstadoDiciplinario()) ? "en orden" : "falta(s) registrada(s)"), "Confirmación", JOptionPane.YES_NO_OPTION);

                            if (result == JOptionPane.YES_OPTION) {
                                if (Logueo.con.agregarCandidatoFacultad(id, asociacion, e.getFacultad().toString(), true)) {
                                    Logueo.padron.buscarAsociacion(asociacion).agregarCandidatoFacultad(id, e.getFacultad(), true);
                                    JOptionPane.showMessageDialog(null, "Candidato agregado con éxito en"
                                            + "la asociación " + asociacion + " para la dignidad " + dignidades.getSelectedItem().toString());
                                } else {
                                    JOptionPane.showMessageDialog(null, "No se agregó el candidato, inténtelo de nuevo más tarde");
                                }
                            } else {
                                JOptionPane.showMessageDialog(null, "No se agregó el candidato");
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Un candidato para esta digniddad ya\n"
                                    + "se encuentra registrado en este partido");
                        }
                    } else if(dignidad == 3){
                        boolean dignidadRegistrada;
                        dignidadRegistrada = Logueo.padron.buscarAsociacion(asociacion).
                                getVicepresidentesFacultad().get(e.getFacultad()) != null;
                        if (!dignidadRegistrada) {
                            int result = JOptionPane.showConfirmDialog(null,
                                    "Información del Estudiante\n\n"
                                    + "Nombres: " + e.getNombre() + " " + e.getApellido()
                                    + "\nFacultad: " + e.getFacultad().toString()
                                    + "\nPromedio General: " + e.getPromedioGeneral()
                                    + "\nEstado Diciplinario: " + ((e.isEstadoDiciplinario()) ? "en orden" : "falta(s) registrada(s)"), "Confirmación", JOptionPane.YES_NO_OPTION);

                            if (result == JOptionPane.YES_OPTION) {
                                if (Logueo.con.agregarCandidatoFacultad(id, asociacion, e.getFacultad().toString(), false)) {
                                    Logueo.padron.buscarAsociacion(asociacion).agregarCandidatoFacultad(id, e.getFacultad(), false);
                                    JOptionPane.showMessageDialog(null, "Candidato agregado con éxito en"
                                            + "la asociación " + asociacion + " para la dignidad " + dignidades.getSelectedItem().toString());
                                } else {
                                    JOptionPane.showMessageDialog(null, "No se agregó el candidato, inténtelo de nuevo más tarde");
                                }
                            } else {
                                JOptionPane.showMessageDialog(null, "No se agregó el candidato");
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Un candidato para esta digniddad ya\n"
                                    + "se encuentra registrado en este partido");
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "El estudiante ya se encuentra como\n"
                            + "candidato en otra dignidad o partido");
                }
            } else {
                JOptionPane.showMessageDialog(null, "El id ingresado no corresponde a\n"
                        + "ningún estudiante.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "El id ingresado es incorrecto");
        }
    }//GEN-LAST:event_ingresarCandidato

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PostularCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PostularCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PostularCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PostularCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PostularCandidato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Ingresarb;
    private javax.swing.JComboBox<String> asociacionesRegistradas;
    private javax.swing.JComboBox<String> dignidades;
    private javax.swing.JLabel ext;
    private javax.swing.JTextField idbanner;
    private javax.swing.JLabel ingresart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
