package capadelcliente;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import capadenegocio.Asociacion;
import capadenegocio.Estudiante;
import capadenegocio.Facultades.Facultad;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Cristian Ceron
 */
public class Visualizar extends javax.swing.JFrame {

    int xMouse, yMouse;

    /**
     * Creates new form Visualizar
     */
    public Visualizar() {
        initComponents();
        this.setLocationRelativeTo(null);
        actualizar();
        ganadores();
    }

    public void actualizar() {
        categoria.removeAllItems();
        categoria.addItem("ASEUDLA GENERAL");
        for (Facultad f : Facultad.values()) {
            categoria.addItem(f.toString());
        }
    }

    public void ganadores() {
        String resultado = "GANADORES PARA CADA DIGNIDAD\n\n";
        String ganadorGeneral = "";
        int votos = 0;
        int i = 0;
        ArrayList<Asociacion> asociaciones = Logueo.padron.getAsociaciones();
        boolean empate = false;
        for (Asociacion a : asociaciones) {
            if (!a.getNombre().equals("blanco")) {
                if (i == 0) {
                    ganadorGeneral = a.getNombre();
                    votos = a.votosTotalesGeneral();
                } else {
                    if (votos < a.votosTotalesGeneral()) {
                        ganadorGeneral = a.getNombre();
                        votos = a.votosTotalesGeneral();
                    } else if (votos == a.votosTotalesGeneral()) {
                        empate = true;
                    }
                }
                i++;
            }
        }
        Estudiante e = Logueo.padron.buscarEstudiante(Logueo.padron.buscarAsociacion(ganadorGeneral).getPresidenteGeneral().getEstudiante());
        resultado += "PRESIDENTE GENERAL: " + (empate ? "EMPATE" : (e.getNombre() + " " + e.getApellido() + "(" + ganadorGeneral + ")")) + "\n";
        e = Logueo.padron.buscarEstudiante(Logueo.padron.buscarAsociacion(ganadorGeneral).getVicepresidenteGeneral().getEstudiante());
        resultado += "VICEPRESIDENTE GENERAL: " + (empate ? "EMPATE" : (e.getNombre() + " " + e.getApellido() + "(" + ganadorGeneral + ")")) + "\n\n";

        for (Facultad f : Facultad.values()) {
            i = 0;
            votos = 0;
            empate = false;
            for (Asociacion as : asociaciones) {
                if (!as.getNombre().equals("blanco")) {
                    if (votos < as.getVotosFaculad().get(f)) {
                        ganadorGeneral = as.getNombre();
                        votos = votos = as.getVotosFaculad().get(f);
                    } else if (votos == as.getVotosFaculad().get(f)) {
                        empate = true;
                    }
                }
            }
            e = Logueo.padron.buscarEstudiante(Logueo.padron.buscarAsociacion(ganadorGeneral).getPresidentesFacultad().get(f).getEstudiante());
            resultado += "PRESIDENTE FACULTAD " + f.toString() + ": " + (empate ? "EMPATE" : (e.getNombre() + " " + e.getApellido() + "(" + ganadorGeneral + ")")) + "\n";
            e = Logueo.padron.buscarEstudiante(Logueo.padron.buscarAsociacion(ganadorGeneral).getVicepresidentesFacultad().get(f).getEstudiante());
            resultado += "VICEPRESIDENTE FACULTAD " + f.toString() + ":" + (empate ? "EMPATE" : (e.getNombre() + " " + e.getApellido() + "(" + ganadorGeneral + ")")) + "\n\n";
        }

        resultados.setText(resultado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        atrasTxtPanel = new javax.swing.JPanel();
        atrasTxt = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        resultados = new javax.swing.JTextArea();
        nextPanel = new javax.swing.JPanel();
        nesttxt = new javax.swing.JLabel();
        nextPanel1 = new javax.swing.JPanel();
        nesttxt1 = new javax.swing.JLabel();
        categoria = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        nextPanel2 = new javax.swing.JPanel();
        nesttxt2 = new javax.swing.JLabel();
        nextPanel3 = new javax.swing.JPanel();
        nesttxt3 = new javax.swing.JLabel();
        nesttxt4 = new javax.swing.JLabel();
        nextPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        equis1Panel = new javax.swing.JPanel();
        equis1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(150, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/udla_logo_blanco.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(763, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        fondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 70));

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 36)); // NOI18N
        jLabel3.setText("RESULTADOS");
        fondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 230, 40));

        atrasTxtPanel.setBackground(new java.awt.Color(255, 255, 255));
        atrasTxtPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        atrasTxtPanel.setPreferredSize(new java.awt.Dimension(30, 30));
        atrasTxtPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atrasTxtPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                atrasTxtPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                atrasTxtPanelMouseExited(evt);
            }
        });

        atrasTxt.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        atrasTxt.setText("<");
        atrasTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atrasTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                atrasTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                atrasTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout atrasTxtPanelLayout = new javax.swing.GroupLayout(atrasTxtPanel);
        atrasTxtPanel.setLayout(atrasTxtPanelLayout);
        atrasTxtPanelLayout.setHorizontalGroup(
            atrasTxtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, atrasTxtPanelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(atrasTxt)
                .addGap(14, 14, 14))
        );
        atrasTxtPanelLayout.setVerticalGroup(
            atrasTxtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, atrasTxtPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(atrasTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        fondo.add(atrasTxtPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 40, 30));

        jScrollPane3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        resultados.setEditable(false);
        resultados.setBackground(new java.awt.Color(236, 234, 234));
        resultados.setColumns(20);
        resultados.setRows(5);
        jScrollPane3.setViewportView(resultados);

        fondo.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 610, 360));

        nextPanel.setBackground(new java.awt.Color(150, 0, 0));
        nextPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nextPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nextPanelMouseExited(evt);
            }
        });

        nesttxt.setFont(new java.awt.Font("Roboto Cn", 1, 14)); // NOI18N
        nesttxt.setForeground(new java.awt.Color(255, 255, 255));
        nesttxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nesttxt.setText("ESTADÍSTICAS TOTALES");
        nesttxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nesttxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                estadisticas(evt);
            }
        });

        javax.swing.GroupLayout nextPanelLayout = new javax.swing.GroupLayout(nextPanel);
        nextPanel.setLayout(nextPanelLayout);
        nextPanelLayout.setHorizontalGroup(
            nextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nextPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nesttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        nextPanelLayout.setVerticalGroup(
            nextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nextPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(nesttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        fondo.add(nextPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, 190, -1));

        nextPanel1.setBackground(new java.awt.Color(150, 0, 0));
        nextPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextPanel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nextPanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nextPanel1MouseExited(evt);
            }
        });

        nesttxt1.setFont(new java.awt.Font("Roboto Cn", 1, 14)); // NOI18N
        nesttxt1.setForeground(new java.awt.Color(255, 255, 255));
        nesttxt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nesttxt1.setText("BUSCAR");
        nesttxt1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nesttxt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscar(evt);
            }
        });

        javax.swing.GroupLayout nextPanel1Layout = new javax.swing.GroupLayout(nextPanel1);
        nextPanel1.setLayout(nextPanel1Layout);
        nextPanel1Layout.setHorizontalGroup(
            nextPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nextPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nesttxt1, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addContainerGap())
        );
        nextPanel1Layout.setVerticalGroup(
            nextPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nesttxt1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        fondo.add(nextPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, 190, -1));

        categoria.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        categoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fondo.add(categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 140, 130, 30));

        jLabel12.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel12.setText("Categoría:");
        fondo.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, -1, 30));

        nextPanel2.setBackground(new java.awt.Color(150, 0, 0));
        nextPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextPanel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nextPanel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nextPanel2MouseExited(evt);
            }
        });

        nesttxt2.setFont(new java.awt.Font("Roboto Cn", 1, 14)); // NOI18N
        nesttxt2.setForeground(new java.awt.Color(255, 255, 255));
        nesttxt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nesttxt2.setText("GANADORES");
        nesttxt2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nesttxt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ganadores(evt);
            }
        });

        javax.swing.GroupLayout nextPanel2Layout = new javax.swing.GroupLayout(nextPanel2);
        nextPanel2.setLayout(nextPanel2Layout);
        nextPanel2Layout.setHorizontalGroup(
            nextPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nextPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nesttxt2, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addContainerGap())
        );
        nextPanel2Layout.setVerticalGroup(
            nextPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nesttxt2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        fondo.add(nextPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 190, -1));

        nextPanel3.setBackground(new java.awt.Color(150, 0, 0));
        nextPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextPanel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nextPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nextPanel3MouseExited(evt);
            }
        });

        nesttxt3.setFont(new java.awt.Font("Roboto Cn", 1, 14)); // NOI18N
        nesttxt3.setForeground(new java.awt.Color(255, 255, 255));
        nesttxt3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nesttxt3.setText("FINALIZAR PROCESO");
        nesttxt3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nesttxt3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                finalizarProceso(evt);
            }
        });

        javax.swing.GroupLayout nextPanel3Layout = new javax.swing.GroupLayout(nextPanel3);
        nextPanel3.setLayout(nextPanel3Layout);
        nextPanel3Layout.setHorizontalGroup(
            nextPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nextPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nesttxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        nextPanel3Layout.setVerticalGroup(
            nextPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nextPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(nesttxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        fondo.add(nextPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, 190, -1));

        nesttxt4.setFont(new java.awt.Font("Roboto Cn", 1, 14)); // NOI18N
        nesttxt4.setForeground(new java.awt.Color(255, 255, 255));
        nesttxt4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nesttxt4.setText("LISTA NO VOTARON");
        nesttxt4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nesttxt4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noVotaron(evt);
            }
        });
        fondo.add(nesttxt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 390, 180, 36));

        nextPanel4.setBackground(new java.awt.Color(150, 0, 0));
        nextPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextPanel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nextPanel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nextPanel4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout nextPanel4Layout = new javax.swing.GroupLayout(nextPanel4);
        nextPanel4.setLayout(nextPanel4Layout);
        nextPanel4Layout.setHorizontalGroup(
            nextPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        nextPanel4Layout.setVerticalGroup(
            nextPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        fondo.add(nextPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 390, -1, -1));

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        equis1Panel.setBackground(new java.awt.Color(250, 250, 250));
        equis1Panel.setPreferredSize(new java.awt.Dimension(30, 30));
        equis1Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                equis1PanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                equis1PanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                equis1PanelMouseExited(evt);
            }
        });

        equis1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        equis1.setText("  X");
        equis1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        equis1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                equis1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                equis1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                equis1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout equis1PanelLayout = new javax.swing.GroupLayout(equis1Panel);
        equis1Panel.setLayout(equis1PanelLayout);
        equis1PanelLayout.setHorizontalGroup(
            equis1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, equis1PanelLayout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(equis1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        equis1PanelLayout.setVerticalGroup(
            equis1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(equis1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(equis1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 770, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(equis1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void equis1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equis1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_equis1MouseClicked

    private void equis1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equis1MouseEntered
        equis1Panel.setBackground(new Color(150, 0, 0));
        equis1.setForeground(Color.WHITE);
    }//GEN-LAST:event_equis1MouseEntered

    private void equis1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equis1MouseExited
        equis1Panel.setBackground(new Color(250, 250, 250));
        equis1.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_equis1MouseExited

    private void equis1PanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equis1PanelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_equis1PanelMouseClicked

    private void equis1PanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equis1PanelMouseEntered
        equis1Panel.setBackground(new Color(150, 0, 0));
        equis1.setForeground(Color.WHITE);
    }//GEN-LAST:event_equis1PanelMouseEntered

    private void equis1PanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equis1PanelMouseExited
        equis1Panel.setBackground(new Color(250, 250, 250));
        equis1.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_equis1PanelMouseExited

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void atrasTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasTxtMouseClicked
        Comite c = new Comite();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_atrasTxtMouseClicked

    private void atrasTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasTxtMouseEntered
        atrasTxtPanel.setBackground(new Color(150, 0, 0));
        atrasTxt.setForeground(Color.WHITE);
    }//GEN-LAST:event_atrasTxtMouseEntered

    private void atrasTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasTxtMouseExited
        atrasTxtPanel.setBackground(Color.WHITE);
        atrasTxt.setForeground(Color.BLACK);
    }//GEN-LAST:event_atrasTxtMouseExited

    private void atrasTxtPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasTxtPanelMouseClicked
        Comite c = new Comite();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_atrasTxtPanelMouseClicked

    private void atrasTxtPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasTxtPanelMouseEntered
        atrasTxtPanel.setBackground(new Color(150, 0, 0));
        atrasTxt.setForeground(Color.WHITE);
    }//GEN-LAST:event_atrasTxtPanelMouseEntered

    private void atrasTxtPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasTxtPanelMouseExited
        atrasTxtPanel.setBackground(Color.WHITE);
        atrasTxt.setForeground(Color.BLACK);
    }//GEN-LAST:event_atrasTxtPanelMouseExited

    private void estadisticas(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estadisticas
        String resultado = "";
        for (Asociacion a : Logueo.padron.getAsociaciones()) {
            if (!a.getNombre().equals("blanco")) {
                resultado += "PARTIDO " + a.getNombre() + "\n\n"
                        + "PRESIDENTE GENERAL : " + Logueo.padron.buscarEstudiante(a.getPresidenteGeneral().getEstudiante()).getNombre() + " " + Logueo.padron.buscarEstudiante(a.getPresidenteGeneral().getEstudiante()).getApellido()
                        + "\nVICEPRESIDENTE GENERAL : " + Logueo.padron.buscarEstudiante(a.getVicepresidenteGeneral().getEstudiante()).getNombre() + " " + Logueo.padron.buscarEstudiante(a.getPresidenteGeneral().getEstudiante()).getApellido() + "\n\n";
                for (Facultad f : Facultad.values()) {
                    resultado += "VOTOS DESDE " + f.toString() + ": " + a.getVotosGeneral().get(f) + "\n";
                }
                resultado += "\n";
                for (Facultad f : Facultad.values()) {
                    resultado += "PRESIDENTE FACULTAD " + f.toString() + ": " + Logueo.padron.buscarEstudiante(a.getPresidentesFacultad().get(f).getEstudiante()).getNombre() + " " + Logueo.padron.buscarEstudiante(a.getPresidentesFacultad().get(f).getEstudiante()).getApellido() + "\n"
                            + "VICEPRESIDENTE FACULTAD " + f.toString() + ": " + Logueo.padron.buscarEstudiante(a.getVicepresidentesFacultad().get(f).getEstudiante()).getNombre() + " " + Logueo.padron.buscarEstudiante(a.getVicepresidentesFacultad().get(f).getEstudiante()).getApellido() + "\n"
                            + "VOTOS: " + a.getVotosFaculad().get(f) + "\n\n";
                }
            }
        }
        Asociacion a = Logueo.padron.buscarAsociacion("blanco");
        resultado += "VOTOS EN BLANCO\n\n"
                + "ASEUDLA GENERAL\n\n";
        for (Facultad f : Facultad.values()) {
            resultado += "VOTOS DESDE " + f.toString() + ": " + a.getVotosGeneral().get(f) + "\n";
        }
        resultado += "\n"
                + "ASEUDLA FACULTADES\n\n";
        for (Facultad f : Facultad.values()) {
            resultado += "VOTOS FACULTAD " + f.toString() + ": " + a.getVotosFaculad().get(f) + "\n";
        }
        resultados.setText(resultado);
    }//GEN-LAST:event_estadisticas

    private void nextPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextPanelMouseClicked

    }//GEN-LAST:event_nextPanelMouseClicked

    private void nextPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextPanelMouseEntered
        nextPanel.setBackground(new Color(200, 0, 0));        // TODO add your handling code here:
    }//GEN-LAST:event_nextPanelMouseEntered

    private void nextPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextPanelMouseExited
        nextPanel.setBackground(new Color(150, 0, 0));        // TODO add your handling code here:
    }//GEN-LAST:event_nextPanelMouseExited

    private void nextPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextPanel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nextPanel1MouseClicked

    private void nextPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextPanel1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_nextPanel1MouseEntered

    private void nextPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextPanel1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_nextPanel1MouseExited

    private void ganadores(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ganadores
        ganadores();
    }//GEN-LAST:event_ganadores

    private void nextPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextPanel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nextPanel2MouseClicked

    private void nextPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextPanel2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_nextPanel2MouseEntered

    private void nextPanel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextPanel2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_nextPanel2MouseExited

    private void buscar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscar
        String resultado = "ESTADÍSTICAS ";
        if (categoria.getSelectedIndex() == 0) {
            resultado += "ASEUDLA GENERAL\n\n";
            for (Asociacion a : Logueo.padron.getAsociaciones()) {
                if (!a.getNombre().equals("blanco")) {
                    resultado += "PARTIDO " + a.getNombre() + "\n\n";
                    Estudiante e = Logueo.padron.buscarEstudiante(a.getPresidenteGeneral().getEstudiante());
                    resultado += "CANDIDATO PRESIDENTE: " + e.getNombre() + " " + e.getApellido() + "\n";

                    e = Logueo.padron.buscarEstudiante(a.getVicepresidenteGeneral().getEstudiante());
                    resultado += "CANDIDATO VICEPRESIDENTE: " + e.getNombre() + " " + e.getApellido() + "\n";
                    resultado += "VOTOS TOTALES: " + a.votosTotalesGeneral() + "\n";

                    for (Facultad f : Facultad.values()) {
                        resultado += "VOTOS DESDE " + f.toString() + ": " + a.getVotosGeneral().get(f) + "\n";
                    }
                    resultado += "\n";
                }
            }
            Asociacion a = Logueo.padron.buscarAsociacion("blanco");
            resultado += "VOTOS EN BLANCO\n\n"
                    + "ASEUDLA GENERAL\n\n";
            for (Facultad f : Facultad.values()) {
                resultado += "VOTOS DESDE " + f.toString() + ": " + a.getVotosGeneral().get(f) + "\n";
            }
        } else {
            String facultad = categoria.getSelectedItem().toString();
            resultado += "ASEUDLA FACULTAD " + facultad + "\n\n";
            for (Asociacion a : Logueo.padron.getAsociaciones()) {
                if (!a.getNombre().equals("blanco")) {
                    resultado += "PARTIDO " + a.getNombre() + "\n\n";
                    Estudiante e = Logueo.padron.buscarEstudiante(a.getPresidentesFacultad().get(Facultad.valueOf(facultad)).getEstudiante());
                    resultado += "CANDIDATO PRESIDENTE: " + e.getNombre() + " " + e.getApellido() + "\n";
                    e = Logueo.padron.buscarEstudiante(a.getVicepresidentesFacultad().get(Facultad.valueOf(facultad)).getEstudiante());
                    resultado += "CANDIDATO VICEPRESIDENTE: " + e.getNombre() + " " + e.getApellido() + "\n";
                    resultado += "VOTOS: " + a.getVotosFaculad().get(Facultad.valueOf(facultad)) + "\n\n";
                }
            }
            Asociacion a = Logueo.padron.buscarAsociacion("blanco");
            resultado += "VOTOS EN BLANCO: " + a.getVotosFaculad().get(Facultad.valueOf(facultad));
        }
        resultados.setText(resultado);
    }//GEN-LAST:event_buscar

    private void nextPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextPanel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nextPanel3MouseClicked

    private void nextPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextPanel3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_nextPanel3MouseEntered

    private void nextPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextPanel3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_nextPanel3MouseExited

    private void finalizarProceso(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_finalizarProceso
        if (Logueo.padron.getEstadoProceso() == 2) {
            if (Logueo.con.actualizarEstadoFinalizado()) {
                Logueo.padron.setEstadoFinalizado();
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo finalizar el proceso, inténtelo de nuevo más tarde");
            }
        } else {
            JOptionPane.showMessageDialog(null, "El proceso ya finalizó");
        }
    }//GEN-LAST:event_finalizarProceso

    private void nextPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextPanel4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nextPanel4MouseClicked

    private void nextPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextPanel4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_nextPanel4MouseEntered

    private void nextPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextPanel4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_nextPanel4MouseExited

    private void noVotaron(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noVotaron
        String resultado = "";
        for(Estudiante e: Logueo.padron.getEstudiantes()){
            if(!e.isaVotado()){
                resultado += "Id Banner: " + e.getIdBanner() + "\n"
                        + "Nombres: " + e.getNombre() + " " + e.getApellido() + "\n\n";
            }
        }
        resultados.setText(resultado);
    }//GEN-LAST:event_noVotaron

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visualizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel atrasTxt;
    private javax.swing.JPanel atrasTxtPanel;
    private javax.swing.JComboBox<String> categoria;
    private javax.swing.JLabel equis1;
    private javax.swing.JPanel equis1Panel;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel nesttxt;
    private javax.swing.JLabel nesttxt1;
    private javax.swing.JLabel nesttxt2;
    private javax.swing.JLabel nesttxt3;
    private javax.swing.JLabel nesttxt4;
    private javax.swing.JPanel nextPanel;
    private javax.swing.JPanel nextPanel1;
    private javax.swing.JPanel nextPanel2;
    private javax.swing.JPanel nextPanel3;
    private javax.swing.JPanel nextPanel4;
    public static javax.swing.JTextArea resultados;
    // End of variables declaration//GEN-END:variables
}
